---
title: "Analysis of JULES1p0 ensemble wave1"
output: html_notebook
---


## Preliminaries
Load libraries, functions and data.

```{r, echo = FALSE, message = FALSE, warning=FALSE, results = 'hide'}
# Load helper functions

knitr::opts_chunk$set(fig.path = "figs/", echo = FALSE, message = FALSE, warnings = FALSE)

# load helper functions, data and do preliminary processing of the ensemble.
source('JULES-ES-1p0-common.R')

```



```{r}

ensloc <- '/scratch/hadaw/jules_postprocess/u-ck006/'

if (file.exists("ensemble_wave01.rdata")) {
  load("ensemble_wave01.rdata")
} else {
  
  
  nstart <- 499
  nend <- 798
  nens <- (nend - nstart) + 1
  datmat_wave01 <- matrix(nrow = nens, ncol = length(y_names_sum))
  colnames(datmat_wave01) <- y_names_sum
  
  enslist <- paste("P", formatC(nstart:nend, width=4, flag="0"), sep="")
  #floc <- paste0(ensloc,ensmember,subdir)
  
  for(i in 1:nens){
    
    vec <- rep(NA, length(y_names_sum))
    
    ensmember <- enslist[i] 
    
    fn <- paste0(ensloc,ensmember,'/stats/','JULES-ES-1p0_',ensmember,'_Annual_global.nc')
    #print(fn)
    
    try(nc <- nc_open(paste0(fn)))
    try(vec <- sapply(y_names_sum, FUN = modernValue, nc = nc, ix = 144:164))
    datmat_wave01[i, ] <- vec
    nc_close(nc)
  }
  
  save(nens, datmat_wave01, enslist, floc, file ="ensemble_wave01.rdata")
}

```

